# Build: build and push image to registry
name: Build & Push (esptool-js)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set images
        run: |
          REPO="$(echo "${{ secrets.REGISTRY }}/${{ gitea.repository }}" | tr '[:upper:]' '[:lower:]')"
          SHORT_SHA="$(echo "${GITHUB_SHA:-unknown}" | cut -c1-7)"
          echo "IMAGE_LATEST=${REPO}:latest" >> $GITHUB_ENV
          echo "IMAGE_SHA=${REPO}:sha-${SHORT_SHA}" >> $GITHUB_ENV

      - name: Docker build
        run: |
          docker build \
            -t "${{ env.IMAGE_LATEST }}" \
            -t "${{ env.IMAGE_SHA }}" \
            -f Dockerfile .

      - name: Docker login
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Docker push
        run: |
          docker push "${{ env.IMAGE_LATEST }}"
          docker push "${{ env.IMAGE_SHA }}"
